### ISSUE TITLE
Implement Camera Support in Render Pipeline

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#36] opened 2014-02-12 20:08 UTC
There should be some method for the game script to set/control the cameras.  Camera class works fine, but the render pipeline doesn't know anything about the camera.

**Comment by dislogical** [comment] 2014-02-12 20:10
Dupe of #21.

**Comment by ericchristenson** [comment] 2014-02-12 21:22
Closed #21, I'm fairly sure this is a different concern.

**Closed as completed** 2014-02-22 19:13 UTC
